patch:
  dev_branch: dev
  tgt_branchs:
    - dev
    - qa

  jira_id: ""
  jira_desc: x

repo:
   dev-tool:
    name: dev-tool
    url:  https://git.yunify.com/chenyu/dev-tool/
    path: /Users/yu/code/git.yunify.com/dev-tool
